### ISSUE TITLE
Desktop apps

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/auth#1]
Add support for
- Linux
- MacOS
- Windows

Work in progress here: [`desktop`](https://github.com/ente-io/auth/tree/desktop).

**Comment by vishnukvmd** [comment]
Closing this, since we've launched a web app @ [auth.ente.io](https://auth.ente.io) :)

**Comment by C-Duv** [comment]
How a web application that requires an authentication is considered the same as a standalone desktop Linux/macOS/Windows application?
