### ISSUE TITLE
website icon

### ISSUE THREAD

**Issue by belarbi2733** [ente-io/auth#114]
it would be great to website icon and also if we can add this manually

Thanks for the great work

**Comment by vishnukvmd** [comment]
Closing in favor of https://github.com/ente-io/auth/issues/5

**Comment by marcoclg19** [comment]
@vishnukvmd We are all waiting for the site icons. Any news for the future? :)

**Comment by vishnukvmd** [comment]
Hey @marcoclg19, swamped with some work on our Photos app right now, will get to this afterwards :)
