### ISSUE TITLE
Emergency: Remove Email Auth Asap

### ISSUE THREAD

**Issue by alien1919** [ente-io/auth#137]
Hi,
I'm really annoyed and frustrated with the Email MFA. This is ridiculous ..
My Email Account is protected with 2FA and You're asking me to provide the code sent to the email address. Does this make any sense ?
I'm out of all my accounts. My Password Manager, Bank Account .. Everything.. I have zero money in my pocket.

Kindly remove this requirement ASAP. At least for me. 
Thanks.

**Comment by ua741** [comment]
In the latest version (v1.0.51), we have added an option `Settings->Security->Email Verification` to enable or disable email verification during login.
