### ISSUE TITLE
[question]How do I delete unwanted tokens?

### ISSUE THREAD

**Issue by a15355447898a** [ente-io/auth#139]
I made a mistake and added the wrong 2fa token to auth, but when I tried to delete it there was no place for me to do so (either in the app or on the website)
Dear developers, please tell me what to do

**Comment by vishnukvmd** [comment]
Hey, please swipe left on the item, and you'll see an option to delete it.

**Comment by a15355447898a** [comment]
> Hey, please swipe left on the item, and you'll see an option to delete it.嘿，请在该项目上向左滑动，您将看到删除它的选项。

Thank you very much!
