### ISSUE TITLE
removing an entry

### ISSUE THREAD

**Issue by QUAKEULUS** [ente-io/auth#164]
how do you remove an entry on android in the app?

**Comment by vishnukvmd** [comment]
Hey, you can swipe left on an entry to remove it.

**Comment by errorgurumeditation** [comment]
the way to do that should probably be changed. maybe a 3-dot menu instead?

**Comment by vishnukvmd** [comment]
We had considered that, but adding 3 dots to each entry was cluttering the UI. Another option is to add a global Edit button to the action bar, clicking which will display an option to edit / delete all entries. It'd be more obvious than the current interaction.

**Comment by QUAKEULUS** [comment]
yeah in only noticed that instruction upon the fresh install of app.

**Comment by ua741** [comment]
Closing this for now. We have added an FAQ mentioning the same.
If more folks run into this problem, we will figure out how can we improve the UX.

**Comment by Merrit** [comment]
I thought it wasn't possible to remove an entry until I found this issue.

I'd recommend having long-press bring up the options for an entry.. I tried this and it just copied the same way a tap does, but it is a common "more options" gesture.
