### ISSUE TITLE
Logging in to a new device using a recovery key logs you out of all existing devices.

### ISSUE THREAD

**Issue by QUAKEULUS** [ente-io/auth#166]
Is this by design?

I wanted to add auth to an older ios device as backup, I got the message:

"Recreate password
The current device is not powerful enough to verify your password, but we can regenerate in a way that works with all devices.
Please login using your recovery key and regenerate your password (you can use the same one again if you wish)."

So I did, but I was logged out of all existing devices as well.

On my existing devices, it wasn't a clean logged out either, instead of giving me a login screen, it popped up the "Setup your first account" screen, then after I closed and re-opened twice I finally got a login screen.

**Comment by ua741** [comment]
> So I did, but I was logged out of all existing devices as well.
Yes, this is expected behaviour (similar to change password). 
To re-encrypted your key with the updated parameters (to support the older device), we initiate a change-password flow.

Regarding the second issue regarding clean logout, we will investigate that. Thank for reporting this.
