### ISSUE TITLE
Excessive memory consumption

### ISSUE THREAD

**Issue by mateus1619** [ente-io/auth#176]
Good morning!

After entering the password, the loading screen appears after all the apps on the device are closed.  

Here's the screenshot, if you need more information, I'm at your disposal.

![Screenshot_20230805-130726.png](https://github.com/ente-io/auth/assets/83937109/87991b49-87c8-4e50-8f0d-1bf4d8dcb652)

**Comment by vishnukvmd** [comment]
Hey! Deriving the key from your password is a memory + cpu intensive operation. Could you please confirm if this memory is not released post key derivation? Thanks!

**Comment by mateus1619** [comment]
> Hey! Deriving the key from your password is a memory + cpu intensive operation. Could you please confirm if this memory is not released post key derivation? Thanks!

Sorry, but I don't know what key derivation is, but the app closes along with all the others, after entering the password when logging in.
So just another smartphone?

**Comment by ua741** [comment]
The app only performs this expensive operation during sign-up, log in, & change-password. Can you confirm if the the app is using excessive memory during regular usage?

**Comment by mateus1619** [comment]
I have 2 smartphones!

1° Moto E5 Play Go;
2° J3 2016;

The 1st never went beyond the login page, due to the reason in question, but the 2nd never had any problems.

**Comment by mateus1619** [comment]
> The app only performs this expensive operation during sign-up, log in, & change-password. Can you confirm if the the app is using excessive memory during regular usage?

I have 2 smartphones!

1° Moto E5 Play Go;
2° J3 2016;

The 1st never went beyond the login page, due to the reason in question, but the 2nd never had any problems.
