### ISSUE TITLE
Allow exporting selected entries (encrypted and unencrypted)

### ISSUE THREAD

**Issue by sken130** [ente-io/auth#185]
Some bad online services do not have concept of organisations, and cannot share a subscribed service to multiple users. Moreover, our bosses refuse to pay for more than one accounts, or find alternatives.

In such case, we are forced to use only one account to login and use their services. Instead of signing up the service using employee1@company.com, employee2@company.com, ... which share the common subscription, we have to sign up with single account shareduser@company.com, and multiple employees share this account to login.

And ironically the bad online service forces us to use TOTP as 2FA method.

In this scenario, we would need a way to allow employee A to share the authenticator secret to employee B, while not exporting his entire 2FA vault. This is why I am raising this feature request.

The export should support both encrypted and unencrypted.

If this feature is also implemented, then ente Auth can completely replace Google Authenticator, and I can safely ask everyone to switch.

Actually export by QR code would be more convenient, but it's not the scope of this feature request.

**Comment by ua741** [comment]
> Actually export by QR code would be more convenient, but it's not the scope of this feature request.

We recently added an option to view QR code. This change will be available in the next release.
https://github.com/ente-io/auth/assets/254676/c1ecee3b-297b-4505-acd4-69dfa33120b5

**Comment by sken130** [comment]
Nice! I think the above view QR code functionality should be enough to address this feature request, as we usually only need to share one entry at a time very occasionally.
