### ISSUE TITLE
Confirm before viewing QR code of an entry

### ISSUE THREAD

**Issue by sken130** [ente-io/auth#192]
Confirm before viewing QR code of an entry, because sometimes we accidentally press it while we try to press Edit. A simple Yes/No dialog (default No) should be enough. The purpose is to avoid letting other people nearby view my QR code by accident.

![Confirm_before_viewing_QR_code_of_an_entry](https://github.com/ente-io/auth/assets/7981861/ee56ea69-ba93-48e9-aa69-bce6c78d4aa2)

**Comment by ua741** [comment]
Thank you for the suggestion. 
In the future, we are planning to add a Advance Section, where we plan to include setting for
- Hide codes by default (show dots) #152 
- Ask for device auth before edit/delete/view Qr Code 
- Pin lock #153

**Comment by ShivamHP** [comment]
Hey @ua741 ! I can take up this issue.
We can ask for device auth(or pin if device auth not available) when the user brings the options on left swiping a code.
If the auth is successful, the user will be shown the edit/delete/show qr options.

**Comment by vishnukvmd** [comment]
Hey @ShivamHP, sounds good! Could you please add authentication on tap for all 3 operations?

**Comment by ShivamHP** [comment]
Hi @vishnukvmd I am trying to use this package for auth: https://pub.dev/packages/local_auth
But I discovered an edge case. What if user do not have local authentication set up (like no biometrics or password)? What should we do in that case?

**Comment by vishnukvmd** [comment]
Hey, we could let it pass, it wouldn't be degraded UX.

**Comment by ShivamHP** [comment]
Hi @vishnukvmd I have made a pull request for this. Can you review it?
