### ISSUE TITLE
(During entry edit) Mask the Secret Key by default, and add a button to show it

### ISSUE THREAD

**Issue by sken130** [ente-io/auth#193]
During entry edit, mask the Secret Key by default, and add a button to show/hide it:

![Edit_mask_secret_key](https://github.com/ente-io/auth/assets/7981861/a4ee6de8-d6d1-409e-b4a9-22c75896e56f)

Because most of the times, we edit the entry only to change the account name and issuer name, and we don't want other people nearby to be able to look at or even take photo of my secret key.

During new entry creation, we may show the secret key by default (keep the button to show/hide it though), as:
1. User may be trying to manually import a lot of entry, so saving him/her a key press will save a lot of time
2. If user is doing this, user won't be doing this with strangers nearby

**Comment by alastairrmcneill** [comment]
Heya @ua741 are you looking for help on this? I'm willing to have a look. Might have a few questions to narrow down what you are looking for though

**Comment by ua741** [comment]
Hello @alastairrmcneill ,
Thank you for showing interest, and YES, we are looking for help! :)  
Please feel free to ask questions either here or on Discord (https://ente.io/discord).

--
If you are new to Flutter, for this particular task, you can check out [_SetupEnterSecretKeyPageState](https://github.com/ente-io/auth/blob/main/lib/onboarding/view/setup_enter_secret_key_page.dart#L17).

- If the code (`widget.code`) inside `_SetupEnterSecretKeyPageState` is null, it means the user is setting up a new secret. If it's not null, then they are editing an existing secret.
- For masking, check out the `obscureText` property of the `TextFormField` widget. You can either create a normal state variable or use a `ValueNotifier`.

**Comment by alastairrmcneill** [comment]
Awesome, thanks @ua741. Please assign this to me. 

I was thinking the textfield would look something like this, with an eye icon button at the end that the user can toggle on and off. This will be set by the `widget.code` that you had above. 
<img width="323" alt="Screenshot 2023-08-22 at 11 08 14" src="https://github.com/ente-io/auth/assets/52216324/838d7920-5bd9-4614-8aed-481529cfb6e1">

**Comment by alastairrmcneill** [comment]
Also I'm new to working on open source projects so sorry if I do something wrong in the process of trying to do the right steps
