### ISSUE TITLE
(During entry edit) Require confirmation during Save if Secret Key is updated

### ISSUE THREAD

**Issue by sken130** [ente-io/auth#194]
If secret key is changed, then when pressing Save button, please provide confirmation dialog "Confirm updating the Secret Key?", as we don't want to update it accidentally, and if we do, it's hard for us to remember the original correct secret key.

Default button is No.

![Edit_alert_if_secret_key_edited](https://github.com/ente-io/auth/assets/7981861/ebdbd530-0fbd-41b7-8581-2420114a504c)

**Comment by alastairrmcneill** [comment]
Heya @ua741 are you able to assign this one to me to work on? 

Do you have a standardised way of handling dialog boxes and actions?

**Comment by ua741** [comment]
Hey @alastairrmcneill ,
Yes, we would probably want to use `showChoiceActionSheet` here to confirm any updation in the secret key during edit.

**Comment by alastairrmcneill** [comment]
Heya @ua741 awesome thanks. I'm not familiar with the localisation that you are using. 
Do you have a help guide for it?
How do I add messages to it?

**Comment by ua741** [comment]
> Heya @ua741 awesome thanks. I'm not familiar with the localisation that you are using.
> Do you have a help guide for it?
> How do I add messages to it?

Hey @alastairrmcneill ,

We have just added a small guide after your comment: 
https://github.com/ente-io/auth/blob/main/CONTRIBUTING.md#localization

Please let us know if you encounter any issues; we'd be happy to help.

**Comment by vishnukvmd** [comment]
Fixed in https://github.com/ente-io/auth/pull/271.
