### ISSUE TITLE
Secret code with spaces

### ISSUE THREAD

**Issue by skariko** [ente-io/auth#20]
Many sites give a phrase with spaces as the secret key for 2FA. Currently Ente Auth does not accept them and you have to delete them manually.

I think it would be much better if it accepted them.

**Comment by vishnukvmd** [comment]
Hey! Could you please provide an example that we could check out? Thank you!

**Comment by skariko** [comment]
> Hey! Could you please provide an example that we could check out? Thank you!

The latest one I have come across is Uber.

The moment I find others if you want I will point them out :)
