### ISSUE TITLE
Handle otpauth URLs saving TOTP.

### ISSUE THREAD

**Issue by marcoclg19** [ente-io/auth#21]
Hi, I wanted to ask if you can add on iOS 16 the possibility to use **ente auth** as an app to do **2FA autofill**. 
(I know Raivo and others have this possibility)

That's what I mean:
https://www.reddit.com/r/1Password/comments/v6pj8q/ios_16_lets_you_use_3rdparty_mfa_apps_with/
https://www.macrumors.com/2022/06/06/ios-16-third-party-two-factor-authentication-support/

**Comment by marcoclg19** [comment]
Maybe I misunderstood myself _with the term autofill_ (which would be great if it could be done one day) and wanted to mean that: 

> "This setting lets you pick a third party app to handle otpauth URLs. i.e. for saving/registering TOTP with third party apps."

**Comment by br0gio** [comment]
I'm pretty sure android also has this feature
