### ISSUE TITLE
Different 2FA codes

### ISSUE THREAD

**Issue by marcoclg19** [ente-io/auth#22]
I noticed that if I log in with the ente auth account on another device, the 2FA codes I have in the account are different for each device. 
Let me explain: On my mobile phone, the app generates some 2FA codes while on the Chromebook it generates others 2FA codes with different numbers. Sites accept the 2FA codes I have on my mobile phone and the ones on the Chromebook are rejected as incorrect.

I don't know what I am doing wrong!

**Comment by vishnukvmd** [comment]
Hey! This sounds like an issue with the system time. Could you please make sure that the clocks on your Chromebook and your mobile phone are in sync?

**Comment by marcoclg19** [comment]
I didn't really notice this! I just restarted the two devices and now they work perfectly. I am such a fool :)

Thank you for your quick response.

**Comment by mnvr** [comment]
@marcoclg19 Glad to know that the issue was the time! Also, I'd say, it's not you, I think this is a problem with the app, we should figure out a better UX to hint the customer that their time might be out of sync - it is easy to not notice and get confused.

That said, I don't quite know where/when to show this. @vishnukvmd Maybe we can show this when the server time and client time are sufficiently out of sync.

**Comment by marcoclg19** [comment]
> @marcoclg19Sono contento di sapere che il problema era il tempo! Inoltre, direi, non sei tu, penso che questo sia un problema con l'app, dovremmo trovare una UX migliore per suggerire al cliente che il suo orario potrebbe non essere sincronizzato: è facile non accorgersene e confondersi .
> 
> Detto questo, non so bene dove/quando mostrarlo.@vishnukvmdForse possiamo mostrarlo quando l'ora del server e l'ora del client non sono sufficientemente sincronizzate.

I am glad I found this service ;)
Some feedback that may be useful: 
- I find the app well made, simple and useful to anyone... the only thing that could be done is perhaps to make the movement of the bar (which tells you how much time is left before the 2FA code expires) more smooth;
- It would be nice to have the icons next to the various 2FAs (like OTP Auth e Raivo);
- Maybe you could put the possibility to rename the devices you are connected to.

Cheers!

**Comment by mnvr** [comment]
> Some feedback that may be useful:

Yes, thank you for taking the time to add your feedback! 

Whilst we can't promise when we'll get around to doing things (while we love and use the auth app too, we have to manage our time vis the photos product). That said, feedback helps a lot in finding out which are the more common requirements, so then we can just focus on implementing those first.

Cheers, and thanks again!
