### ISSUE TITLE
Delete Ente Auth account?

### ISSUE THREAD

**Issue by dustojnikhummer** [ente-io/auth#244]
I accidentally pressed Cancel when saving the account recovery key. Is there a way to delete my Ente Auth account so I can start over?

**Comment by dustojnikhummer** [comment]
I didn't realize I can only do it from the mobile app. Closing the ticket.

**Comment by vishnukvmd** [comment]
@dustojnikhummer Just so you know, you can access your Recovery Key from Settings > Security.

**Comment by dustojnikhummer** [comment]
> @dustojnikhummer Just so you know, you can access your Recovery Key from Settings > Security.

Yes, I realized when I recreated my account. I know it falls out of the scope of this particular ticket, but it should be on the WebUI. Or at least a mentions of where you can access those functions. But thanks for the help!
