### ISSUE TITLE
Authentication prompt after closing the app (iOS)

### ISSUE THREAD

**Issue by MooseExplorer637** [ente-io/auth#250]
When the user has Lockscreen enabled in the settings, the app asks the user to authenticate also when closing the app which isn't needed.

**Comment by ua741** [comment]
If you are still facing the issue in the latest version (v2.0.22), can you please share more details about the device and OS version.

**Comment by MooseExplorer637** [comment]
The latest update also fixed the issue for me. Closing this as completed.
