### ISSUE TITLE
[Bug] Sending TOTP Verification to Email with no account

### ISSUE THREAD

**Issue by shucking** [ente-io/auth#257]
Hi, I mistakenly entered an incorrect email when logging in to Ente Auth via browser. I received a TOTP code on that email and attempted to login to Ente Auth using that TOTP code - I promptly received a message from the web app saying the code has expired. 

Ente Auth should not be sending a TOTP code to an email that is not associated an Ente Auth account.

**Comment by vishnukvmd** [comment]
Hey, internally we're using the same system to register and verify email addresses.

If you click on "Login", and enter an email address that does not exist on our systems, and verify the code, the app will then prompt you to set a password, completing the registration flow. So this simplifies the UX as well.

The other side effect is that it makes it difficult to brute force and identify the emails that are registered in our systems.

So we'll let the current flow remain for now. Thank you for reaching out though!
