### ISSUE TITLE
Add password manager

### ISSUE THREAD

**Issue by alefra1181** [ente-io/auth#263]
Please add a password manager with the ability to encrypt information and link it to cloud services such as Google Drive and... to this wonderful app.

**Comment by tomsik-radek** [comment]
> Please add a password manager with the ability to encrypt information and link it to cloud services such as Google Drive and... to this wonderful app.

Honestly, if it will rely on a 3rd party cloud storage (or local storage), why not just use any Keepass derivative, or Bitwarden?

**Comment by alefra1181** [comment]
Honestly, I dont want to use a few programs to manage the password..I saw the Microsoft Authenticator app and said to myself, I wish your app was like that ..I didnt communicate with the user interface of the Microsoft Authenticator app, it also didnt link to my email properly and didnt save some information .. And doesnt encrypt the information .. 
BitWarden dont encrypt the information sent to the cloud service .. and dont have good security .. If you can do this, it will be great ..
The only app that has relatively good security is Enpass, which crashes on Android phones when you want to connect it to Google Drive.  :(

**Comment by tomsik-radek** [comment]
> Honestly, I dont want to use a few programs to manage the password..I saw the Microsoft Authenticator app and said to myself, I wish your app was like that ..I didnt communicate with the user interface of the Microsoft Authenticator app, it also didnt link to my email properly and didnt save some information .. And doesnt encrypt the information .. BitWarden dont encrypt the information sent to the cloud service .. and dont have good security .. If you can do this, it will be great .. The only app that has relatively good security is Enpass, which crashes on Android phones when you want to connect it to Google Drive. :(

Do you have any proof that Bitwarden doesn't encrypt their data? https://community.bitwarden.com/t/are-urls-encrypted/47213/6

Again, use KeePass then.

**Comment by rafaelazvdo** [comment]
> Honestly, I dont want to use a few programs to manage the password..I saw the Microsoft Authenticator app and said to myself, I wish your app was like that ..I didnt communicate with the user interface of the Microsoft Authenticator app, it also didnt link to my email properly and didnt save some information .. And doesnt encrypt the information .. 
> BitWarden dont encrypt the information sent to the cloud service .. and dont have good security .. If you can do this, it will be great ..
> The only app that has relatively good security is Enpass, which crashes on Android phones when you want to connect it to Google Drive.  :(

Does this mean that the existing encryption options in the account security settings are simply fake or useless?

**Comment by tomsik-radek** [comment]
> > Honestly, I dont want to use a few programs to manage the password..I saw the Microsoft Authenticator app and said to myself, I wish your app was like that ..I didnt communicate with the user interface of the Microsoft Authenticator app, it also didnt link to my email properly and didnt save some information .. And doesnt encrypt the information ..
> > BitWarden dont encrypt the information sent to the cloud service .. and dont have good security .. If you can do this, it will be great ..
> > The only app that has relatively good security is Enpass, which crashes on Android phones when you want to connect it to Google Drive.  :(
> 
> Does this mean that the existing encryption options in the account security settings are simply fake or useless?

I know we are off topic to Ente here, but I really don't like your unfounded accusations towards Bitwarden here. Not affiliated, just a happy customer of theirs. @alefra1181 here hasn't given a single proof of Bitwarden not being encrypted. As show in the post I shared, everything except your registration email address is encrypted, including password notes (which I remember not being encrypted up until a few years back)

**Comment by rafaelazvdo** [comment]
> > > Honestly, I dont want to use a few programs to manage the password..I saw the Microsoft Authenticator app and said to myself, I wish your app was like that ..I didnt communicate with the user interface of the Microsoft Authenticator app, it also didnt link to my email properly and didnt save some information .. And doesnt encrypt the information ..
> > > BitWarden dont encrypt the information sent to the cloud service .. and dont have good security .. If you can do this, it will be great ..
> > > The only app that has relatively good security is Enpass, which crashes on Android phones when you want to connect it to Google Drive.  :(
> > 
> > Does this mean that the existing encryption options in the account security settings are simply fake or useless?
> 
> I know we are off topic to Ente here, but I really don't like your unfounded accusations towards Bitwarden here. Not affiliated, just a happy customer of theirs. @alefra1181 here hasn't given a single proof of Bitwarden not being encrypted. As show in the post I shared, everything except your registration email address is encrypted, including password notes (which I remember not being encrypted up until a few years back)

Well, anyway, my question was ironic, I'm a user of KeepassXC and KeepassDX and I recently started using Bitwarden, I even subscribed to the premium service to be able to use my Yubikeys keys, the service gives me security and I'm sure that what the dev above stated is not a fact.

**Comment by rafaelazvdo** [comment]
> > > Honestly, I dont want to use a few programs to manage the password..I saw the Microsoft Authenticator app and said to myself, I wish your app was like that ..I didnt communicate with the user interface of the Microsoft Authenticator app, it also didnt link to my email properly and didnt save some information .. And doesnt encrypt the information ..
> > > BitWarden dont encrypt the information sent to the cloud service .. and dont have good security .. If you can do this, it will be great ..
> > > The only app that has relatively good security is Enpass, which crashes on Android phones when you want to connect it to Google Drive.  :(
> > 
> > Does this mean that the existing encryption options in the account security settings are simply fake or useless?
> 
> I know we are off topic to Ente here, but I really don't like your unfounded accusations towards Bitwarden here. Not affiliated, just a happy customer of theirs. @alefra1181 here hasn't given a single proof of Bitwarden not being encrypted. As show in the post I shared, everything except your registration email address is encrypted, including password notes (which I remember not being encrypted up until a few years back)

Well, anyway, my question was ironic, I am a user of KeepassXC and KeepassDX and I recently started using Bitwarden, I even subscribed to the premium service to be able to use my Yubikeys keys, the service gives me security and I am sure that what the Issue author stated, it is not a fact.

**Comment by rafaelazvdo** [comment]
> > > Honestly, I dont want to use a few programs to manage the password..I saw the Microsoft Authenticator app and said to myself, I wish your app was like that ..I didnt communicate with the user interface of the Microsoft Authenticator app, it also didnt link to my email properly and didnt save some information .. And doesnt encrypt the information ..
> > > BitWarden dont encrypt the information sent to the cloud service .. and dont have good security .. If you can do this, it will be great ..
> > > The only app that has relatively good security is Enpass, which crashes on Android phones when you want to connect it to Google Drive.  :(
> > 
> > Does this mean that the existing encryption options in the account security settings are simply fake or useless?
> 
> I know we are off topic to Ente here, but I really don't like your unfounded accusations towards Bitwarden here. Not affiliated, just a happy customer of theirs. @alefra1181 here hasn't given a single proof of Bitwarden not being encrypted. As show in the post I shared, everything except your registration email address is encrypted, including password notes (which I remember not being encrypted up until a few years back)

Well, anyway, my question was ironic, I am a user of KeepassXC and KeepassDX and I recently started using Bitwarden, I even subscribed to the premium service to be able to use my Yubikeys keys, the service gives me security and I am sure that what the Issue author stated is not a fact.

**Comment by ua741** [comment]
Sorry, we don't have any plan or bandwidth to build a password manager.
