### ISSUE TITLE
ente Verification Code : This message seems dangerous

### ISSUE THREAD

**Issue by DareDevil2000** [ente-io/auth#265]
![screenshot_150_scrubbed](https://github.com/ente-io/auth/assets/64276640/17cc92db-9f2b-47cd-b905-c67bd487ecaa)

**Comment by vishnukvmd** [comment]
Hey, could you please click on `Looks safe`? Maybe if enough customers mark us as safe, the overlords at Google will have mercy on us 🙏

**Comment by DareDevil2000** [comment]
Why is this happening?

**Comment by vishnukvmd** [comment]
We aren't sure, we've verified all necessary attributes (like the headers, DKIM, SPF and DMAR). One possibility is that they don't like the image we've embedded, we'll try removing it and see if that makes a difference.

**Comment by DareDevil2000** [comment]
Wah, try it, and suppose it's not a virus or spam since it's an open source software or service, I marked it as safe .
