### ISSUE TITLE
Request for New Language Translation

### ISSUE THREAD

**Issue by TomerPacific** [ente-io/auth#281]
Language name: Hebrew

I'd like to offer adding the ability to support Hebrew as a language for the application.
I can help in translating.

**Comment by vishnukvmd** [comment]
Hey @TomerPacific, thanks for offering to help!

Here you go: https://crowdin.com/project/ente-authenticator-app/he

Let us know on Crowdin if you need any assistance.

**Comment by TomerPacific** [comment]
@vishnukvmd  - Thanks. I am working on translating and I know you closed this issue, but I wanted to ask if I could possibly have a PR approved for the translating work I am doing?

**Comment by vishnukvmd** [comment]
Hey, so Crowdin automatically creates a pull request once you're update the translation on their portal. We will simply merge it then.

**Comment by TomerPacific** [comment]
@vishnukvmd  - Finished translating.
