### ISSUE TITLE
Ipad -prompts for biometrics when leaving ente

### ISSUE THREAD

**Issue by Morse6690** [ente-io/auth#329]
When biometrics are activated on my iPad mini 6, with fingerprint sensor, the fingerprint is required to open the app as expected. 
However after changing screens to leave the app, to the home screen of the iPad or to another app, I am prompted once again to "unlock" using biometric verification. 

When leaving the ente the "unlock" biometric screen should not appear. 

IPad mini 6
Ios 17.1.

**Comment by MooseExplorer637** [comment]
I reported [the same issue](https://github.com/ente-io/auth/issues/250) some time ago, but no response yet.

**Comment by Morse6690** [comment]
Looks like these devs have been swamped with more issues as the app has gained pupularity. But my experience has been nothing but positive from them so far. I'm sure they're into it.

**Comment by ua741** [comment]
Can you please upgrade the app and let us know if you are still facing this issue in the latest version v2.0.17.

**Comment by Morse6690** [comment]
Hi. Yep I currently have this version installed. V2.0.17.
The please authenticate screen still appears as described above.

**Comment by Morse6690** [comment]
I just installed V2.0.22.
The issue has been resolved. Thanks for your awesome work!
