### ISSUE TITLE
When codes are hidden, display the copied one(s) for a few seconds after the action

### ISSUE THREAD

**Issue by x80486** [ente-io/auth#331]
## Description

Currently, there is a setting to hide the generated codes. Problem is that there is no good way to see the 2FA code (that was copied) when we tap on the entry in question.

> I haven't seen a way to hide the codes in the Web application, so this is in relationship with the mobile application.

## Describe the Solution You Would Like

When the entry is tapped (and the 2FA code is copied), display the code(s) for a fixed amount of time, say `10` seconds — regardless of the `30` seconds expiration time.

## Describe Alternatives You've Considered

Paste the 2FA code somewhere to be able to see it :grimacing:

## Additional Context

This is really not a big deal when the 2FA code is used in the same mobile device where `ente Auth` is installed, but it becomes a little bit of a problem when we have to use it on a computer or laptop.

**Comment by ua741** [comment]
>  Problem is that there is no good way to see the 2FA code (that was copied) when we tap on the entry in question.

Double tapping on the entry makes the code visible. Please feel free to re-open or create another issue if that doesn't solve the problem.
