### ISSUE TITLE
Add a seperate text field for the icon and the name of the issuer

### ISSUE THREAD

**Issue by Imzxhir** [ente-io/auth#342]
**Is your feature request related to a problem? Please describe.**
In my opinion, I find it annoying when an icon is available in the simpleicons repo but when I named my issuer something different, it will not find the icon unless you do a specific name, which is kinda annoying since I want to use that logo unser a different issuer name.

**Describe the solution you'd like**
I would like a feature where the user could input the issuer name and below it, a text field which the user can enter the icon name and maybe ente auth could try to find it or similiar ones based on what you entered. It would be even better if ente gave suggestions on what icons to use for the logo.

**Describe alternatives you've considered**
One alternative I have considered is to maybe have a toggle for the user to interact with and then it will show the thing I described above.

**Additional context**
Sorry if this was not explained the best, I hope you understand what I am trying to request here.

**Comment by vishnukvmd** [comment]
Hey, this is already on our roadmap, closing this in favor of the existing entry @ https://github.com/ente-io/auth/issues/253
