### ISSUE TITLE
is Android ,if system language is not support(my setting is chinese), display default language is not english

### ISSUE THREAD

**Issue by awkj** [ente-io/auth#37]
I think should add english to setup as default

**Comment by mnvr** [comment]
Thank you for reporting this! We hadn't run into this case earlier, will fix it now.

**Comment by mnvr** [comment]
@awkj we have made a release for fixing this. the fixed version 1.0.25 is already live on GitHub (https://github.com/ente-io/auth/releases/tag/v1.0.25) and on the play store.

Thank your for reporting!

**Comment by awkj** [comment]
Thanks, very fast, looking forward to the desktop version
