### ISSUE TITLE
Save exported codes as file

### ISSUE THREAD

**Issue by rafalkk** [ente-io/auth#380]
I don't know if this is a bug or there is no such option. When I click export, I can only send the file to recently used contacts, use the "share nearby" function or select some random apps.

Of course, I would like it to be possible to save 'ente-authenticator-codes.txt' using file manager. 

system: Android 12
in the first blurry row are contacts
![ss](https://github.com/ente-io/auth/assets/54404141/cb04f38e-911c-464f-a858-eb7942b77861)

**Comment by arznwang** [comment]
It's indeed a problem, it's not very convenient to use like this.
