### ISSUE TITLE
No screenshot protection

### ISSUE THREAD

**Issue by hereisadi** [ente-io/auth#390]
**Is your feature request related to a problem? Please describe.**
Platform Android: Currently there is no screenshot protection, which is very crucial and industry standard for an authenticator app. Although we can hide the 2fa codes by tweaking the settings, and app do ask for authentication when lock screen is turned on, but malicious apps can capture the screenshot in background.
 
**Describe the solution you'd like**
Additionally, under the lock screen if turned on, should prevent capturing screenshots.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vishnukvmd** [comment]
Should be fixed by https://github.com/ente-io/auth/commit/1a654fe7484c3e09aba6e35fb858a0e482b1f74b.
