### ISSUE TITLE
decrypt tool for Linux and amd64 architecture

### ISSUE THREAD

**Issue by digitalfredy** [ente-io/auth#398]
Problem:

The actual binary named decrypt does not work in Linux , I check and the binary looks like Mac arm:

```
file /usr/local/bin/decrypt 
/usr/local/bin/ente-decrypt: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

**Describe the solution you'd like**
Modify your CI to build binaries for Linux amd 64 and probably for other platforms

**Describe alternatives you've considered**
If the answer is please compile it, I could try but not right now because I'm doing a migration.

PS: Thanks for made auth Open Source!

**Comment by ua741** [comment]
Can you help us in testing the binary from [here](https://github.com/ente-io/auth/tree/binary_allplatform/migration-guides/decrypt/bin)


PS: We have added a [script](https://github.com/ente-io/auth/blob/binary_allplatform/migration-guides/decrypt/release.sh) to generate the same using `source code`. Eventually, we will decrypt this tool and move the logic inside [ente-cli](https://github.com/ente-io/cli)

**Comment by digitalfredy** [comment]
> Can you help us in testing the binary from [here](https://github.com/ente-io/auth/tree/binary_allplatform/migration-guides/decrypt/bin)
> 
> PS: We have added a [script](https://github.com/ente-io/auth/blob/binary_allplatform/migration-guides/decrypt/release.sh) to generate the same using `source code`. Eventually, we will decrypt this tool and move the logic inside [ente-cli](https://github.com/ente-io/cli)

The provided link in "testing from here" is broken (404)

Just provide the right link and I will test it on Linux

Thanks for the rapid answer!

**Comment by ua741** [comment]
Sorry, the underlying branch was deleted after merge. Please download the binary from [here](https://github.com/ente-io/auth/tree/main/migration-guides/decrypt/bin). 

You can use ‘uname -a’ command to identify the arch

**Comment by digitalfredy** [comment]
Thanks! 

- `ente-decrypt-linux-amd64` tested and it works


some feedback:

> Usage: ./decrypt <export_file> <password> <output_file>

- `export_file` is not clear, probably `ente_encrypted_file`?
- output file should be optional, if absent print in the standard output and will help us to be creative using pipelines
- password should be optional, if not provided ask for it in the standard input
  - in the actual way the password stay in the shell history
 - But keep the possibility to use as it is now because is great while working with many files.
