### ISSUE TITLE
Black icons are hard to see in dark mode

### ISSUE THREAD

**Issue by lukasbestle** [ente-io/auth#403]
**Describe the bug**
If a service uses the icon from Simple Icons and the brand color is black (`#000000`), ente Auth displays the icon in black, even if dark mode is enabled. This makes the icon hard to see (black on dark grey).

**To Reproduce**
1. Switch the app to dark mode
2. Create a TOTP entry for a service with a black or very dark icon (e.g. CodePen)

**Expected behavior**
Black or very dark icons should be flipped to white when the app is in dark mode. This would also avoid having to duplicate icons from Simple Icons to grey custom icons (like with GitHub at the moment). All those black icons would automatically be displayed correctly.

**Possible implementations**
- Easiest, but does not catch all cases: If the brand color is `#000000` and dark mode is active, use `#ffffff` as brand color
- More elaborate: If the brand color is neutral grey (R, G and B values are the same), calculate the lightness of the color. In dark mode, check if the lightness is below e.g. 10%. In light mode, check if the lightness is above e.g. 90%. In these cases, flip the lightness (e.g convert 7% to 93%).

**Screenshots**
![Example with CodePen](https://github.com/ente-io/auth/assets/1595007/6ed7d51b-86f6-4462-9298-6660cd559d9e)

**Smartphone (please complete the following information):**
iPhone 13 mini, iOS 16.7.2, ente Auth 2.0.25

**Comment by aadarsh-patel** [comment]
Hey @vishnukvmd ,
I'd like to work on this

**Comment by vishnukvmd** [comment]
Hey @aadarsh-patel, you can find the code-point to modify the behavior here: https://github.com/ente-io/auth/blob/8b9592c06e85e8978dd1d4f0a90e5db6d6f31df3/lib/ui/utils/icon_utils.dart#L73
