### ISSUE TITLE
White background after initial launch in dark mode

### ISSUE THREAD

**Issue by BionicBison05** [ente-io/auth#420]
**Describe the bug**
In dark mode, after the initial launch, when the app is opened or viewed in the app switcher, the auth logo is shown in a black square as expected, but the rest of the background is blindingly white.

**To Reproduce**
1. Make sure the app is closed entirely from the App Switcher
2. Have dark mode enabled
3. Launch the app, observing expected black background
4. Open App Switcher or simply go to home screen and back into app, observing black square on unexpected white background

**Expected behavior**
App launch screen background is completely black, even after the first launch

**Screenshots**
Initial launch:
![IMG_0746](https://github.com/ente-io/auth/assets/93722725/943f15b8-5238-47c5-bfd9-dbb21aaba889)

Opening app again after initial launch:
![IMG_0744](https://github.com/ente-io/auth/assets/93722725/30bf3979-c273-4bf7-acf6-10ba294162ce)

App Switcher:
![IMG_0745](https://github.com/ente-io/auth/assets/93722725/4306d647-37a8-40d8-b66b-e208efa88a36)

**Smartphone:**
 - Device: iPhone 14 Pro Max
 - OS: iOS 17.2.1
 - Browser: N/A
 - Version: 2.0.30

**Comment by vishnukvmd** [comment]
Hey, could you please confirm if the app's theme is different from the system's theme?

**Comment by BionicBison05** [comment]
I can confirm that the app does switch its theme correctly along with my system theme.

**Comment by vishnukvmd** [comment]
This should be fixed by #411

Have just pushed the release to AppStore. Will keep this open until the update is live.

**Comment by vishnukvmd** [comment]
@BionicBison05 the update is now live. Please reopen if this does not fix the issue!
