### ISSUE TITLE
Error accessing the vault from Chrome

### ISSUE THREAD

**Issue by Guuustav** [ente-io/auth#434]
**Describe the bug**
In the login process, after entering the password this message appears:
Application error: a client-side exception has occurred (see the browser console for more information).

**Desktop (please complete the following information):**
 - macOS Ventura 13.6.3 and Monterey 12.7.2
 - I can't acces with Google Chrome 120.0.6099.234 (Build oficial) (x86_64)
 - I can access with Safari 17.2 (18617.1.17.11.11, 18617)

I only managed to log in one day after reloading the page several times and entering the password several times. So I'm stuck to using Auth from the phone only.

* EDIT: I managed to log into Chrome but it tells me to download the mobile app.

![Captura de pantalla 2024-01-28 a las 13 50 33](https://github.com/ente-io/auth/assets/99183395/961c7508-c722-47b8-b6de-55ab79440330)

Thanks in advance.

**Comment by vishnukvmd** [comment]
Hey, currently the web app only supports viewing of codes.

We're currently working on a desktop app that has feature-parity with mobile. Please hold on until then 🙂

**Comment by Guuustav** [comment]
> Hey, currently the web app only supports viewing of codes.
> 
> We're currently working on a desktop app that has feature-parity with mobile. Please hold on until then 🙂

The codes are what I want. I was just wondering how to solve the error in Chrome (my main browser) because in Safari I log in without problems. Thanks in advance.

**Comment by vishnukvmd** [comment]
Sorry, when I read
> EDIT: I managed to log into Chrome

I assumed that all was well.

Could you please share the error you're seeing on the console? It'll help us understand where things are breaking. Thanks!

**Comment by Guuustav** [comment]
> Sorry, when I read
> 
> > EDIT: I managed to log into Chrome
> 
> I assumed that all was well.
> 
> Could you please share the error you're seeing on the console? It'll help us understand where things are breaking. Thanks!

I had tried for several days and could never log in using Chrome. To my surprise, today I have accessed the first one. I don't know if they have made any modifications to the website to correct the problem I had.

**Comment by vishnukvmd** [comment]
Likely because the first time you logged in there were no codes to be rendered.

We only support viewing of existing codes on the web.

I'll close this issue for now, if you've more questions, feel free to reopen!

**Comment by Guuustav** [comment]
I logged in again without problems. I don't know what was happening, but I tried several days for several weeks and I only managed to log in once. Now there is no problem. Thank you very much for your support.
