### ISSUE TITLE
Unable to login to ente auth iOS app on iPhone 8

### ISSUE THREAD

**Issue by rarikuma** [ente-io/auth#456]
When I try to log into the ente auth iOS app on my iPhone 8, I get the following text and cannot log in.
What does this mean?
![IMG_0031](https://github.com/ente-io/auth/assets/135856005/74910a99-3450-4c3c-b9ef-ea032e8a99ab)

I am able to log in with the same account on the web ente auth in Chrome on Windows and the ente auth Android app, and it should not be a mistake in the password.

**Smartphone**
 - Device: [iPhone 8]
 - OS: [iOS15.5]
 - Version [v0.8.56]

**Comment by vishnukvmd** [comment]
This means that your current device (iPhone 8) is not as powerful as the original device where a key was derived from your password.

So using a recovery key to reset your password will derive a new key that will be compatible across all your devices. Recommend that :)

**Comment by vishnukvmd** [comment]
It's the compute and memory available to apps that determine the "power" of a device.

If one does not meet our expectations, we half it while doubling the other, to ensure that over all complexity remains the same.

You can find more details here: https://github.com/ente-io/auth/blob/5faf32a2b8f536ebc561979e1ec904e64191e80c/lib/utils/crypto_util.dart#L382-L390

**Comment by rarikuma** [comment]
Thank you for your response.
I appreciate the detailed disclosure of how it works.

My ente auth account was first opened on the web with Chrome on Windows and a password was set, at that point I could log in on my iPhone 8.
I then changed the password from the ente auth Android app on my Android device and now I cannot log in from my iPhone 8.
This means that setting the ente auth password from the Android device is more power than from the Windows PC, why do you think this is?
The Windows PC on which I initially set the password has much better hardware specs than the Android device.

**Comment by vishnukvmd** [comment]
It's very likely that the browser is capping either the memory or the compute requirements. Likely the former.

While the Android app is able to run free.

**Comment by vishnukvmd** [comment]
No, it'll be a constant. When we reduce memory requirements, we increase compute requirements (and vice versa). If we detect an insecure device, we prevent account creation.

https://github.com/ente-io/auth/blob/5faf32a2b8f536ebc561979e1ec904e64191e80c/lib/utils/crypto_util.dart#L429
