### ISSUE TITLE
Logging in error

### ISSUE THREAD

**Issue by TechFanTheo** [ente-io/auth#462]
**Describe the bug**
When log-in into auth.ente.io/auth, a ; (semi-colon) appears at the bottom left of the screen for a short time. It doesn't impact the functionality since it disappears when the loading  process is over.

Not the end of the world, but a fix will be welcome, since I guess this is due to a string error in the website code.

Edit: on some occasion, the error can also be seen **before** login.
**To Reproduce**
1. Go to 'auth.ente.io/auth'
2. Click on 'Log in'
3. See error

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Brave]
 - Version [1.62]

**Comment by mnvr** [comment]
Hey, thank you for reporting this! This should be fixed now. Please reopen this issue if you still see this happening.
