### ISSUE TITLE
Email verification code not being sent during account creation.

### ISSUE THREAD

**Issue by nsmith543** [ente-io/auth#467]
**Describe the bug**
I am attempting to create an Ente Auth account, but I am not receiving the initial email verification code as part of onboarding. I have attempted to create the account from both the iOS client, and via the web @ auth.ente.io. After entering my gmail email address (it is correct) and choosing a password, I am taken to the "Verification Code Sent" page. No email arrives after repeated attempts from numerous devices and network connections. It is not in SPAM. Requesting "resend code" also doesn't work.

**To Reproduce**
1. Go to auth.ente.io or download the ente auth iOS app
2. Create a new account tied to a gmail address.
3. No verification code will arrive, so sign-up cannot complete.

**Expected behavior**
A verification code is received at the sign-up email address, allowing for completion of account creation.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 17.3.1

**Comment by vishnukvmd** [comment]
@nsmith543 could you check your spam folder please?

**Comment by nsmith543** [comment]
Hi Vishnu, I apologize for my oversight. I was under the assumption that
the “All Mail” category in Gmail included the contents of SPAM. This is
clearly not the case.

The codes were in SPAM and I’m now signed up successfully. Feel free to
close the issue.

Thanks for the quick reply.

Cheers,
Nathan
