### ISSUE TITLE
Logos for entries

### ISSUE THREAD

**Issue by rywz** [ente-io/auth#5]
Most auth apps have logos, and it would be good to see same thing on ente.

**Comment by asdfzxcvbn** [comment]
Raivo has a [repository](https://github.com/raivo-otp/issuer-icons) full of icons that could be used. Maybe it could be helpful?

**Comment by skariko** [comment]
> Raivo has a [repository](https://github.com/raivo-otp/issuer-icons) full of icons that could be used. Maybe it could be helpful?

Also Authenticator Pro (https://github.com/jamie-mh/AuthenticatorPro) my actually 2FA app. It also allows another feature that is very interesting to me: using custom logos that are saved in the backup created.

**Comment by errorgurumeditation** [comment]
theres also [aegis-icons](https://github.com/aegis-icons/aegis-icons), which may be useful for this
