### ISSUE TITLE
Problem with app language (iPhone, iOS 16.3)

### ISSUE THREAD

**Issue by marcoclg19** [ente-io/auth#54]
If I go like in the settings to change email ~~or something else~~, the popup that appears is not in English like the whole app but appears in German. (iOS 16.3)

**Comment by marcoclg19** [comment]
Indeed, I have tried hitting every option in the settings. The problem persists ONLY if I press the button to change email: the popup, that opens immediately after pressing, it is in German.

**Comment by ua741** [comment]
Hello,

Can you please confirm you app version? You can view that at the bottom of the settings menu. We had fixed this issue in our previous release.

**Comment by marcoclg19** [comment]
> Can you please confirm you app version?

I have the latest version: 1.0.28 
I restarted the device too but that didn't work.

**Comment by mnvr** [comment]
@marcoclg19 looks like there was another case that got overlooked, have fixed it now - https://github.com/ente-io/auth/pull/55. The fix will be in the next release for the app (in a few days).

Thank you for reporting! 🙏

**Comment by marcoclg19** [comment]
There's a new problem! 
I've updated to 1.0.30 and if I press to change mail, I get a grey full screen.

**Comment by ua741** [comment]
> There's a new problem! @ua741 @mnvr I've updated to 1.0.30 and if I press to change mail, I get a grey full screen.

Sorry about that. [Fix](https://github.com/ente-io/auth/pull/60) will be released soon.

Thank you again!
