### ISSUE TITLE
Some entries are no longer showing / empty white spaces in search results

### ISSUE THREAD

**Issue by uD4ra** [ente-io/auth#57]
I have updated to latest release `1.0.28` after that some of entries are no longer showing and there's a white empty places in the app.

![image](https://user-images.githubusercontent.com/12265797/218297232-170f9bde-c088-4944-a116-e1a283289124.jpeg)

When I search one of hidden entries, they appear in search results but there's some white empty spaces along with it.

![image](https://user-images.githubusercontent.com/12265797/218297254-98cc84ab-505d-4ae9-8f67-453c0379e7df.jpeg)

**Comment by ua741** [comment]
Hello,
I am sorry you ran into this bug. Unfortunately, we haven't seen this issue in our testing/day to day usage of the app. Could you please:

-  Turn on error reporting (Settings -> Support -> Crash & Error Reporting)
-  Close and reopen the app
-  Send us a bug report (Settings -> Support -> Report bugs)

Thanks for your help!

**Comment by uD4ra** [comment]
> Hello,
> 
> I am sorry you ran into this bug. Unfortunately, we haven't seen this issue in our testing/day to day usage of the app. Could you please:
> 
> 
> 
> -  Turn on error reporting (Settings -> Support -> Crash & Error Reporting)
> 
> -  Close and reopen the app
> 
> -  Send us a bug report (Settings -> Support -> Report bugs)
> 
> 
> 
> Thanks for your help!

Already done!

**Comment by ua741** [comment]
Hello @uD4ra 

Can you please upgrade the app? We have fixed one issue during code generation.

Thank you for your patience and help.
