### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by sv3nnie** [ente-io/auth#6]
I use 2FA on over 50 different services, so I would love it if I could search for specific services through the app based on issuer and/or account.

**Comment by uD4ra** [comment]
Totally agree with this issue. I wish there's a search bar for specific sites.

I have almost 50 entries in enteAuth, but unfortunately I have to scroll down and look out for what I needed most of the time.

**Comment by SkypLabs** [comment]
Search has been added to the latest release version (v1.0.28). I think this issue can now be closed.
