### ISSUE TITLE
Possible security issue on ente auth web

### ISSUE THREAD

**Issue by ashutoshsaboo** [ente-io/auth#94]
Thanks for all your hard work in developing ente auth! Really appreciate the same! I wanted to report the below issue, as I had just stumbled upon it the other day.

If you close the ente auth webapp tab (without logging out, or deleting the session), and once you re-open it after some time (not sure about exact threshold that's configured in backend - can ente team folks confirm about this please?), it prompts you to enter password before actually seeing the 2FA entries. As might be intuitive - this is a really nice security feature, so that no one can randomly access your ente auth webapp 2fa entries once you are logged in on your machine. 

Now the weird thing is that if you never close the ente auth webapp tab, it won't auto-timeout to show the password popup in the same tab, and keeps on showing the 2fa entries always. Atleast this was the case in my usage of the webapp while it was open for long (i had accidentally forgotten to close the tab) and when i came post few hours i think it was still showing me the 2fa entries. Ideally this should not be the case as it opens up unnecessary room for unauthorised access if at all you accidentally leave your tab open. It should ideally auto time out and force-popup the lock screen even if the tab is kept forever and not closed.  As you can imagine this might be especially important in the context of a 2fa app, as it has secrets data. Can this be please added? 

To be clear: I don't know if in case this feature is already there in place, and if I couldn't see the lockscreen in the same tab due to the threshold of that lockscreen popping up is higher than what I saw after. If this feature is already in place, can the ente team please mention what that timeout is configured to be and if it can be potentially reduced? Like I mentioned, I have by no means done any stress testing for this - i just bumped into this issue as I had accidentally left my tab open. 

cc: @vishnukvmd @ua741

**Comment by vishnukvmd** [comment]
Hey @ashutoshsaboo, there is no timer for the lock screen. If the page reloads, and your keys are no-longer available, the app will automatically redirect you to the password-entry-page to derive the keys. This is probably what happened here.

**Comment by ashutoshsaboo** [comment]
Thanks @vishnukvmd . should we add the timer then for a lock screen for a similar behaviour even when the tab is not closed, in lieu of the fact that this is basically secret data?

**Comment by ashutoshsaboo** [comment]
thank you!

**Comment by ashutoshsaboo** [comment]
> "If the page reloads, and your keys are no-longer available, the app will automatically redirect you to the password-entry-page to derive the keys"

@vishnukvmd do you know after how much time threshold on opening a new ente auth tab, are these keys auto expired?

**Comment by vishnukvmd** [comment]
Hey, the keys are retained in memory. There is no explicit timeout attached. If you close the tabs, the keys will need to be derived from your passphrase again.

**Comment by ashutoshsaboo** [comment]
Gotcha that makes sense, thank you!
